version: "3.8"

services:
  backend:
    image: juwono136/inventorcs-backend:latest
    pull_policy: always
    container_name: inventorcs-backend
    restart: always
    environment:
      PORT: ${PORT}
      CONNECTION_URL: ${CONNECTION_URL}
      DB_NAME: ${DB_NAME}
      CLIENT_URL: ${CLIENT_URL}
      INTERNET_SERVER: ${INTERNET_SERVER}
      API_USERS_URL: ${API_USERS_URL}
      NODE_ENV: ${NODE_ENV}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      ACTIVATION_TOKEN_SECRET: ${ACTIVATION_TOKEN_SECRET}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      RABBITMQ_URL: ${RABBITMQ_URL}
    ports:
      - "5001:5001"
    networks:
      - csbiweb-tunnel

  frontend:
    image: juwono136/inventorcs-frontend:latest
    pull_policy: always
    container_name: inventorcs-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:5173"
    networks:
      - csbiweb-tunnel

volumes:
  mongodb_data:

networks:
  csbiweb-tunnel:
    external: true
