name: InventorCS

on:
  push:
    branches:
      - master
    paths-ignore:
      - "README.md"
  pull_request:
    branches:
      - master

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Backend Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/inventorcs-backend:latest ./server
          docker push ${{ secrets.DOCKER_USERNAME }}/inventorcs-backend:latest

      - name: Build and Push Frontend Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/inventorcs-frontend:latest ./client
          docker push ${{ secrets.DOCKER_USERNAME }}/inventorcs-frontend:latest

  continuous-deployment:
    needs: continuous-integration
    runs-on: self-hosted

    steps:
      - name: Pull Latest Backend Image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/inventorcs-backend:latest

      - name: Pull Latest Frontend Image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/inventorcs-frontend:latest

      - name: Stop and Remove Old Containers
        run: |
          cd $GITHUB_WORKSPACE
          docker-compose down || true
          docker system prune -f

      - name: Run New Containers
        run: |
          cd $GITHUB_WORKSPACE
          docker-compose up -d

      - name: Add Containers to Tunnel
        run: |
          docker network connect ${{ secrets.TUNNEL_NAME }} inventorcs-backend || true
          docker network connect ${{ secrets.TUNNEL_NAME }} inventorcs-frontend || true
